/**
 * Contemplators dataset — 100 silent figures.
 * Each Contemplator has 5 attributes used by the Atlas to compute matches,
 * plus identifiers (id, number, slug) used to build URLs to the rest of the site.
 *
 * Generated from the master Contemplators spreadsheet.
 * Do NOT edit by hand — regenerate from source if data changes.
 */

export type ObjectOfContemplation = "thoughts" | "nature" | "silence" | "art" | "people";
export type MentalState = "curiosity" | "calm" | "empathy" | "nostalgia" | "openness";
export type Environment = "horizon" | "shore" | "empty_space" | "crowded_place" | "sacred_refuge";
export type SensitiveVector = "abstraction" | "immersion" | "lightness" | "depth" | "intensity";
export type ContemplativeLink = "opening" | "waiting" | "attention" | "observation" | "listening";

export interface Contemplator {
  id: number;             // 1..100
  number: string;         // formatted with leading zeros, e.g. "#001", "#042", "#100"
  name: string;           // colloquial name (e.g. "Alabau Ito")
  slug: string;           // URL-safe slug, e.g. "contemplator-001" — used to link to the site
  phrase: string;         // poetic phrase in English
  image: string;          // Cloudinary URL
  object: ObjectOfContemplation;
  state: MentalState;
  environment: Environment;
  vector: SensitiveVector;
  link: ContemplativeLink;
}

export const CONTEMPLATORS: Contemplator[] = [
  {
    id: 1,
    number: "#001",
    name: "Alabau Ito",
    slug: "contemplator-001",
    phrase: "Before the horizon of your own thoughts, curiosity becomes a luminous wound: you are not seeking an answer, you are opening a crack for the unknown to enter.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989321/ALABAU_ITO_i3fzfl.png",
    object: "thoughts",
    state: "curiosity",
    environment: "horizon",
    vector: "abstraction",
    link: "opening",
  },
  {
    id: 2,
    number: "#002",
    name: "Olive",
    slug: "contemplator-002",
    phrase: "Nature receives you like a shore without noise; you enter it slowly, and calm opens a space where even time seems to bow its head.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989383/CONTEMPLATOR_2_wtqqsy.png",
    object: "nature",
    state: "calm",
    environment: "shore",
    vector: "immersion",
    link: "opening",
  },
  {
    id: 3,
    number: "#003",
    name: "Fortune",
    slug: "contemplator-003",
    phrase: "You approach nature not to possess it, but to wait with it; in that abstract distance, empathy learns to breathe like a contained tide.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989270/CONTEMPLATOR_3_sfxhav.png",
    object: "nature",
    state: "empathy",
    environment: "shore",
    vector: "abstraction",
    link: "waiting",
  },
  {
    id: 4,
    number: "#004",
    name: "Aero",
    slug: "contemplator-004",
    phrase: "In the architectural void, silence does not rest: it surrounds you like a cold memory, and nostalgia immerses you in what still keeps watch from the edges.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989262/CONTEMPLATOR_4_sjfwm8.png",
    object: "silence",
    state: "nostalgia",
    environment: "empty_space",
    vector: "immersion",
    link: "attention",
  },
  {
    id: 5,
    number: "#005",
    name: "Black Falcon",
    slug: "contemplator-005",
    phrase: "Before the horizon, art touches you with the lightness of a final ember; it does not break in, it waits, and you learn to receive its radiance without breaking it.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989246/CONTEMPLATOR_5_hqlkca.png",
    object: "art",
    state: "openness",
    environment: "horizon",
    vector: "lightness",
    link: "waiting",
  },
  {
    id: 6,
    number: "#006",
    name: "Solara",
    slug: "contemplator-006",
    phrase: "You look at art as one enters still water at the end of the day: with full attention, letting the form cover you before you say your name.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989306/CONTEMPLATOR_6_qkqp52.png",
    object: "art",
    state: "openness",
    environment: "horizon",
    vector: "immersion",
    link: "attention",
  },
  {
    id: 7,
    number: "#007",
    name: "Bianco",
    slug: "contemplator-007",
    phrase: "Although the place is crowded, nature calls to you from an untouched depth; calm sharpens your gaze until it makes clear what everyone passes through without seeing.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989315/CONTEMPLATOR_7_dim8y8.png",
    object: "nature",
    state: "calm",
    environment: "crowded_place",
    vector: "depth",
    link: "attention",
  },
  {
    id: 8,
    number: "#008",
    name: "NoxBlue",
    slug: "contemplator-008",
    phrase: "Beneath the refuge's half-light, art appears like an electric reliquary; you observe it with nostalgia and discover that the abstract can also burn like a prayer.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989283/CONTEMPLATOR_8_zsnr5k.png",
    object: "art",
    state: "nostalgia",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "observation",
  },
  {
    id: 9,
    number: "#009",
    name: "Solaris",
    slug: "contemplator-009",
    phrase: "The horizon offers itself like a canvas not yet sworn to, and your curiosity, light yet precise, attends to the art that is born where the air seems weightless.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989334/CONTEMPLATOR_9_dqlioq.png",
    object: "art",
    state: "curiosity",
    environment: "horizon",
    vector: "lightness",
    link: "attention",
  },
  {
    id: 10,
    number: "#010",
    name: "Anastasia",
    slug: "contemplator-010",
    phrase: "You observe people like a city remembering itself from the shore; nostalgia intensifies every gesture until it becomes a sign impossible to ignore.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989333/CONTEMPLATOR_10_czyxi6.png",
    object: "people",
    state: "nostalgia",
    environment: "shore",
    vector: "intensity",
    link: "observation",
  },
  {
    id: 11,
    number: "#011",
    name: "Sahar",
    slug: "contemplator-011",
    phrase: "There are faces that ask nothing of you: they only ask you to remain. From that human shore, calm immerses you in a clean, almost solar waiting.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989310/CONTEMPLATOR_11_ldmlra.png",
    object: "people",
    state: "calm",
    environment: "shore",
    vector: "immersion",
    link: "waiting",
  },
  {
    id: 12,
    number: "#012",
    name: "Canvas",
    slug: "contemplator-012",
    phrase: "In art's refuge, calm is not rest but openness; the abstract rises slowly and teaches you to enter the sacred without noise.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989503/CONTEMPLATOR_12_pqr4kx.png",
    object: "art",
    state: "calm",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "opening",
  },
  {
    id: 13,
    number: "#013",
    name: "Latexia",
    slug: "contemplator-013",
    phrase: "Between severe surfaces and motionless air, art compels you to attend to the smallest thing; there calm becomes geometry and abstraction acquires the weight of destiny.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989298/CONTEMPLATOR_13_ula51r.png",
    object: "art",
    state: "calm",
    environment: "empty_space",
    vector: "abstraction",
    link: "attention",
  },
  {
    id: 14,
    number: "#014",
    name: "Akakaze",
    slug: "contemplator-014",
    phrase: "Even among others, you perceive nature's fragility as a light breath; empathy makes you attentive to what barely brushes the world.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989298/CONTEMPLATOR_14_yoqyrp.png",
    object: "nature",
    state: "empathy",
    environment: "crowded_place",
    vector: "lightness",
    link: "attention",
  },
  {
    id: 15,
    number: "#015",
    name: "Nocturna",
    slug: "contemplator-015",
    phrase: "Your thoughts resound like a room abandoned and still alive; curiosity pulls you inward, where the architectural void begins to speak first.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989284/CONTEMPLATOR_15_ab8v0w.png",
    object: "thoughts",
    state: "curiosity",
    environment: "empty_space",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 16,
    number: "#016",
    name: "Valentino Plata",
    slug: "contemplator-016",
    phrase: "Art lets itself be seen from afar, almost industrial and vulnerable, and you observe it with a gentle empathy that honors even what was made to harden.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989521/CONTEMPLATOR_16_ihklqd.png",
    object: "art",
    state: "empathy",
    environment: "horizon",
    vector: "lightness",
    link: "observation",
  },
  {
    id: 17,
    number: "#017",
    name: "Grex",
    slug: "contemplator-017",
    phrase: "Before the presence of others, you choose not to invade: you wait. And in that shared refuge, empathy takes on a light form, almost merciful.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989325/CONTEMPLATOR_17_ccb8th.png",
    object: "people",
    state: "empathy",
    environment: "sacred_refuge",
    vector: "lightness",
    link: "waiting",
  },
  {
    id: 18,
    number: "#018",
    name: "Aili",
    slug: "contemplator-018",
    phrase: "Under the murmur of the crowded place, your thoughts descend like a secret well; with curiosity you hear what is forming below, where no one else seems willing to enter.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989267/CONTEMPLATOR_18_ejug21.png",
    object: "thoughts",
    state: "curiosity",
    environment: "crowded_place",
    vector: "depth",
    link: "listening",
  },
  {
    id: 19,
    number: "#019",
    name: "Lunelle",
    slug: "contemplator-019",
    phrase: "The crowd falls away as you listen in nature to an intimate, ancient echo, and nostalgia draws you into a serene, dense immersion with no immediate way out.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989522/CONTEMPLATOR_19_ghslo8.png",
    object: "nature",
    state: "nostalgia",
    environment: "crowded_place",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 20,
    number: "#020",
    name: "Nazar",
    slug: "contemplator-020",
    phrase: "Your thoughts do not arrive as noise, but as golden symbols asking for shelter; in that inner refuge, empathy opens the abstract until it becomes revelation.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989523/CONTEMPLATOR_20_mikqj4.png",
    object: "thoughts",
    state: "empathy",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "opening",
  },
  {
    id: 21,
    number: "#021",
    name: "Aka Oni",
    slug: "contemplator-021",
    phrase: "Art arrives the way the sea arrives when it still cannot be seen: it enters the body first, then immerses you, and finally lets you understand its wound.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989491/CONTEMPLATOR_21_kk3j6t.png",
    object: "art",
    state: "empathy",
    environment: "shore",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 22,
    number: "#022",
    name: "Yami no Kai",
    slug: "contemplator-022",
    phrase: "Before nature you do not advance: you consent. You allow its depth to reach you from the horizon and, in that waiting, something hardened in you learns to yield.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989490/CONTEMPLATOR_22_adezin.png",
    object: "nature",
    state: "openness",
    environment: "horizon",
    vector: "depth",
    link: "waiting",
  },
  {
    id: 23,
    number: "#023",
    name: "Horizon",
    slug: "contemplator-023",
    phrase: "There are thoughts that sit with you as if they came from another dawn; you hold them in silence, and nostalgia makes them abstract, intimate, almost invocable.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989507/CONTEMPLATOR_23_xeclch.png",
    object: "thoughts",
    state: "nostalgia",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "waiting",
  },
  {
    id: 24,
    number: "#024",
    name: "Spook",
    slug: "contemplator-024",
    phrase: "Nature appears here as a geometric, weightless promise; you observe it calmly, letting the horizon settle an unexpected clarity within you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989530/CONTEMPLATOR_24_oit2pg.png",
    object: "nature",
    state: "calm",
    environment: "horizon",
    vector: "lightness",
    link: "observation",
  },
  {
    id: 25,
    number: "#025",
    name: "Velune",
    slug: "contemplator-025",
    phrase: "A blazing tide sets you to listening to art; its intensity does not wound you, it awakens you, and curiosity leads you to the shore where color dictates its own law.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989322/CONTEMPLATOR_25_p9gxca.png",
    object: "art",
    state: "curiosity",
    environment: "shore",
    vector: "intensity",
    link: "listening",
  },
  {
    id: 26,
    number: "#026",
    name: "Corven",
    slug: "contemplator-026",
    phrase: "Silence spreads its feathers through the void and does not protect you: it exposes you. Nostalgia gives it intensity, and you open yourself to that darkness with a strange obedience.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989531/CONTEMPLATOR_26_zslfc9.png",
    object: "silence",
    state: "nostalgia",
    environment: "empty_space",
    vector: "intensity",
    link: "opening",
  },
  {
    id: 27,
    number: "#027",
    name: "Kaira",
    slug: "contemplator-027",
    phrase: "Surrounded by the presence of others, you open yourself to people as one enters a smoke-filled memory; nostalgia immerses you and makes sacred what once seemed ordinary.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989278/CONTEMPLATOR_27_rejsw6.png",
    object: "people",
    state: "nostalgia",
    environment: "crowded_place",
    vector: "immersion",
    link: "opening",
  },
  {
    id: 28,
    number: "#028",
    name: "Barrilete",
    slug: "contemplator-028",
    phrase: "You seek in nature a sign deeper than the landscape, and by observing it from the refuge, curiosity reveals a depth that asks for no explanation.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989292/CONTEMPLATOR_28_blrftx.png",
    object: "nature",
    state: "curiosity",
    environment: "sacred_refuge",
    vector: "depth",
    link: "observation",
  },
  {
    id: 29,
    number: "#029",
    name: "Acid",
    slug: "contemplator-029",
    phrase: "Like old tapes that still retain electricity, your thoughts begin to sound again; curiosity immerses you in that retro refuge where the past keeps broadcasting its secret.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989534/CONTEMPLATOR_29_cbcruk.png",
    object: "thoughts",
    state: "curiosity",
    environment: "sacred_refuge",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 30,
    number: "#030",
    name: "Ember",
    slug: "contemplator-030",
    phrase: "There is a lunar intensity in the memory of others; you listen to it from the refuge of nostalgia, and each presence gives back something you thought extinguished.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989245/CONTEMPLATOR_30_zxabv1.png",
    object: "people",
    state: "nostalgia",
    environment: "sacred_refuge",
    vector: "intensity",
    link: "listening",
  },
  {
    id: 31,
    number: "#031",
    name: "Blue Noir",
    slug: "contemplator-031",
    phrase: "In the void left by people when they depart, nostalgia raises a secret architecture; you remain there, waiting for depth to finish pronouncing its truth.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989244/CONTEMPLATOR_31_dmvxce.png",
    object: "people",
    state: "nostalgia",
    environment: "empty_space",
    vector: "depth",
    link: "waiting",
  },
  {
    id: 32,
    number: "#032",
    name: "Avena",
    slug: "contemplator-032",
    phrase: "Your thoughts grow quiet like wood beneath an impossible light; in that refuge, attention refines the abstract until it begins to resemble a form of wisdom.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989253/CONTEMPLATOR_32_thaqlq.png",
    object: "thoughts",
    state: "calm",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "attention",
  },
  {
    id: 33,
    number: "#033",
    name: "Latte",
    slug: "contemplator-033",
    phrase: "Silence, too, can be fertile and strange; when you open yourself to it with curiosity, the refuge grows light and the invisible begins to bloom.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989253/CONTEMPLATOR_33_zrtomn.png",
    object: "silence",
    state: "curiosity",
    environment: "sacred_refuge",
    vector: "lightness",
    link: "opening",
  },
  {
    id: 34,
    number: "#034",
    name: "Bronzor",
    slug: "contemplator-034",
    phrase: "You observe people from a ceremonial stillness; the emptiness around them lifts them from the world and allows you to enter their presence as one enters an ancient vessel.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989275/CONTEMPLATOR_34_mwbzmg.png",
    object: "people",
    state: "calm",
    environment: "empty_space",
    vector: "immersion",
    link: "observation",
  },
  {
    id: 35,
    number: "#035",
    name: "Oxen",
    slug: "contemplator-035",
    phrase: "Silence looks farther than you do. That is why you wait before the horizon, letting curiosity turn the abstract into a question of stone and time.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989383/CONTEMPLATOR_35_xtg0yj.png",
    object: "silence",
    state: "curiosity",
    environment: "horizon",
    vector: "abstraction",
    link: "waiting",
  },
  {
    id: 36,
    number: "#036",
    name: "Carboni",
    slug: "contemplator-036",
    phrase: "There are silences that do not pacify: they consecrate. This one settles over you with calm, and as you observe its abstract form you discover a refuge without doors or witnesses.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989287/CONTEMPLATOR_36_uvyzfd.png",
    object: "silence",
    state: "calm",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "observation",
  },
  {
    id: 37,
    number: "#037",
    name: "Plumyx",
    slug: "contemplator-037",
    phrase: "Amid the crowd, people take on an unexpected gravity; nostalgia opens depth within them, and you observe how every body carries a different night inside.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989293/CONTEMPLATOR_37_ykkdzn.png",
    object: "people",
    state: "nostalgia",
    environment: "crowded_place",
    vector: "depth",
    link: "observation",
  },
  {
    id: 38,
    number: "#038",
    name: "Lucien",
    slug: "contemplator-038",
    phrase: "You do not force thought: you receive it like a ritual flare. In the inner refuge, its intensity demands waiting, because certain visions arrive only when haste ceases.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989504/CONTEMPLATOR_38_sr5kaz.png",
    object: "thoughts",
    state: "openness",
    environment: "sacred_refuge",
    vector: "intensity",
    link: "waiting",
  },
  {
    id: 39,
    number: "#039",
    name: "Aura",
    slug: "contemplator-039",
    phrase: "Art reaches you from a suspended edge; you receive it without touching it, letting its lightness inhabit the void like a lamp that learned to wait.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989266/CONTEMPLATOR_39_m9vxon.png",
    object: "art",
    state: "openness",
    environment: "empty_space",
    vector: "lightness",
    link: "waiting",
  },
  {
    id: 40,
    number: "#040",
    name: "Esmora",
    slug: "contemplator-040",
    phrase: "Before the mental horizon, you impose no form: you let it come. And when it arrives, intense and mineral, it opens you inward like a newly consecrated architecture.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989261/CONTEMPLATOR_40_f7ybjn.png",
    object: "thoughts",
    state: "openness",
    environment: "horizon",
    vector: "intensity",
    link: "opening",
  },
  {
    id: 41,
    number: "#041",
    name: "Imperial",
    slug: "contemplator-041",
    phrase: "Nature does not always offer itself as landscape; sometimes it becomes sign, ruin, threshold. You receive it that way, in waiting, until its abstraction begins to shelter you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989307/CONTEMPLATOR_41_pgpk3z.png",
    object: "nature",
    state: "openness",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "waiting",
  },
  {
    id: 42,
    number: "#042",
    name: "Tablor",
    slug: "contemplator-042",
    phrase: "In the midst of human abundance, you observe with empathy the silent intensity of each life; none is empty, all burn, even if from afar they seem in order.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989490/CONTEMPLATOR_42_wcte4j.png",
    object: "people",
    state: "empathy",
    environment: "crowded_place",
    vector: "intensity",
    link: "observation",
  },
  {
    id: 43,
    number: "#043",
    name: "Velora",
    slug: "contemplator-043",
    phrase: "Silence falls over the place like an ancient curtain; you remain inside it, immersed, while nostalgia turns the emptiness into a room that still remembers you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989301/CONTEMPLATOR_43_vjy69v.png",
    object: "silence",
    state: "nostalgia",
    environment: "empty_space",
    vector: "immersion",
    link: "waiting",
  },
  {
    id: 44,
    number: "#044",
    name: "Eclipse",
    slug: "contemplator-044",
    phrase: "At the edge of color, art becomes farewell and fire; you observe it with nostalgia, knowing its intensity does not want to save you, but to mark you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989513/CONTEMPLATOR_44_rppjwh.png",
    object: "art",
    state: "nostalgia",
    environment: "shore",
    vector: "intensity",
    link: "observation",
  },
  {
    id: 45,
    number: "#045",
    name: "Estela",
    slug: "contemplator-045",
    phrase: "Even if you are surrounded, you do not harden: you open yourself. And that calm allows you to enter the presence of others as one sinks into water still untouched.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989316/CONTEMPLATOR_45_yi3ai8.png",
    object: "people",
    state: "calm",
    environment: "crowded_place",
    vector: "immersion",
    link: "opening",
  },
  {
    id: 46,
    number: "#046",
    name: "Lumix",
    slug: "contemplator-046",
    phrase: "Nature appears here like an ancient glow among voices and bodies; you wait for it with nostalgia, and its intensity passes through you like a revelation that needs no temple.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989514/CONTEMPLATOR_46_yhqi1o.png",
    object: "nature",
    state: "nostalgia",
    environment: "crowded_place",
    vector: "intensity",
    link: "waiting",
  },
  {
    id: 47,
    number: "#047",
    name: "Humizor",
    slug: "contemplator-047",
    phrase: "You observe how nature persists even in the most worn places; you receive it in its abstract, faint, urban form, like one recognizing moss on the metal of the world.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989382/CONTEMPLATOR_47_uqpqwl.png",
    object: "nature",
    state: "openness",
    environment: "crowded_place",
    vector: "abstraction",
    link: "observation",
  },
  {
    id: 48,
    number: "#048",
    name: "Fernando",
    slug: "contemplator-048",
    phrase: "Nothing is superfluous, and that is why you attend. In the architectural void, art becomes light and exact, and your receptivity is enough for something minimal to become unforgettable.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989276/CONTEMPLATOR_48_trncea.png",
    object: "art",
    state: "openness",
    environment: "empty_space",
    vector: "lightness",
    link: "attention",
  },
  {
    id: 49,
    number: "#049",
    name: "Pancho",
    slug: "contemplator-049",
    phrase: "Your thoughts enter the refuge like stray creatures: rough, aflame, necessary. You do not fear them; you observe them until their intensity reveals a form of truth.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989513/CONTEMPLATOR_49_epmzeh.png",
    object: "thoughts",
    state: "openness",
    environment: "sacred_refuge",
    vector: "intensity",
    link: "observation",
  },
  {
    id: 50,
    number: "#050",
    name: "Timber",
    slug: "contemplator-050",
    phrase: "Even surrounded, you choose a silent compassion. You wait within it until immersion shows you that every crowd is, at heart, a sum of solitudes.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989254/CONTEMPLATOR_50_ixc1bg.png",
    object: "silence",
    state: "empathy",
    environment: "crowded_place",
    vector: "immersion",
    link: "waiting",
  },
  {
    id: 51,
    number: "#051",
    name: "Sora",
    slug: "contemplator-051",
    phrase: "At the shore, silence does not erase the past: it deepens it. You watch it grow beneath the light, and nostalgia takes on the clean pulse of what returned too late.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989132/CONTEMPLATOR_51_lqz9xg.png",
    object: "silence",
    state: "nostalgia",
    environment: "shore",
    vector: "depth",
    link: "observation",
  },
  {
    id: 52,
    number: "#052",
    name: "Magnus",
    slug: "contemplator-052",
    phrase: "There is a kind of calm that does not extinguish the fire, only arranges it. That is how you contemplate nature among others: intense, burning, observed like an omen at dusk.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989227/CONTEMPLATOR_52_fwbcxh.png",
    object: "nature",
    state: "calm",
    environment: "crowded_place",
    vector: "intensity",
    link: "observation",
  },
  {
    id: 53,
    number: "#053",
    name: "Halvorsen",
    slug: "contemplator-053",
    phrase: "Your thoughts rise weightless, almost like a figure being tested by light; you attend to that lightness and the inner horizon begins to answer you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989168/CONTEMPLATOR_53_xckbfs.png",
    object: "thoughts",
    state: "openness",
    environment: "horizon",
    vector: "lightness",
    link: "attention",
  },
  {
    id: 54,
    number: "#054",
    name: "Zambrano",
    slug: "contemplator-054",
    phrase: "Curiosity keeps you awake before the horizon of nature; you look deeper than the obvious, until depth returns to you a new question.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989133/CONTEMPLATOR_54_b45hhi.png",
    object: "nature",
    state: "curiosity",
    environment: "horizon",
    vector: "depth",
    link: "attention",
  },
  {
    id: 55,
    number: "#055",
    name: "Wang",
    slug: "contemplator-055",
    phrase: "Amid human noise, nature offers itself with a strange, almost mechanical lightness; you open yourself to it and discover that the fragile, too, can sustain you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989162/CONTEMPLATOR_55_rgsrkk.png",
    object: "nature",
    state: "openness",
    environment: "crowded_place",
    vector: "lightness",
    link: "opening",
  },
  {
    id: 56,
    number: "#056",
    name: "Montemayor",
    slug: "contemplator-056",
    phrase: "You listen to people the way one listens to the night once the moon has decided to remain; curiosity immerses you in their contours until the distant becomes intimate.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989162/CONTEMPLATOR_56_bvnxis.png",
    object: "people",
    state: "curiosity",
    environment: "horizon",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 57,
    number: "#057",
    name: "Obsidian",
    slug: "contemplator-057",
    phrase: "Beyond the face, you listen to people in the refuge of the essential; your curiosity embraces the abstract until presence becomes a pure sign.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989162/CONTEMPLATOR_57_a0ahsv",
    object: "people",
    state: "curiosity",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "listening",
  },
  {
    id: 58,
    number: "#058",
    name: "Nebula",
    slug: "contemplator-058",
    phrase: "In the severe void where everything seems held back, curiosity opens you to the intensity of people; you discover that even darkness emits tiny calls.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989135/CONTEMPLATOR_58_eicf4e.png",
    object: "people",
    state: "curiosity",
    environment: "empty_space",
    vector: "intensity",
    link: "opening",
  },
  {
    id: 59,
    number: "#059",
    name: "Geumbit",
    slug: "contemplator-059",
    phrase: "Your thoughts shine like an old coin in an uninhabited room; you do not interrupt them. You wait for their intensity to settle and reveal the hidden design of the void.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989134/CONTEMPLATOR_59_w6etij.png",
    object: "thoughts",
    state: "curiosity",
    environment: "empty_space",
    vector: "intensity",
    link: "waiting",
  },
  {
    id: 60,
    number: "#060",
    name: "Jin",
    slug: "contemplator-060",
    phrase: "You approach your thoughts with a rare compassion, like someone waiting by the water without demanding form from it; from that shore, depth begins to trust you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989169/CONTEMPLATOR_60_qgo8uf.png",
    object: "thoughts",
    state: "empathy",
    environment: "shore",
    vector: "depth",
    link: "waiting",
  },
  {
    id: 61,
    number: "#061",
    name: "Cazuel",
    slug: "contemplator-061",
    phrase: "You attend to a domestic silence, almost vegetal, where nostalgia simmers slowly; from the shore of the humble, intensity arises without announcement and the everyday reaches the dignity of ritual.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989227/CONTEMPLATOR_61_vpcw5j.png",
    object: "silence",
    state: "nostalgia",
    environment: "shore",
    vector: "intensity",
    link: "attention",
  },
  {
    id: 62,
    number: "#062",
    name: "Carmin",
    slug: "contemplator-062",
    phrase: "Art lets itself be seen like a serene creature that no longer needs to prove anything; in the refuge, calm makes even its most abstract gestures visible.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989125/CONTEMPLATOR_62_nxqg1f.png",
    object: "art",
    state: "calm",
    environment: "sacred_refuge",
    vector: "abstraction",
    link: "observation",
  },
  {
    id: 63,
    number: "#063",
    name: "Aviar",
    slug: "contemplator-063",
    phrase: "Empathy leads you to look at nature not as landscape, but as an organism that contemplates you back; there the horizon acquires an almost moral depth.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989137/CONTEMPLATOR_63_nnptow.png",
    object: "nature",
    state: "empathy",
    environment: "horizon",
    vector: "depth",
    link: "attention",
  },
  {
    id: 64,
    number: "#064",
    name: "Peso Pluma",
    slug: "contemplator-064",
    phrase: "Your thoughts know the weight of the world, but you do not judge them; you await them at the shore of their intensity until empathy frees them from their own noise.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989174/CONTEMPLATOR_64_b8ie0e.png",
    object: "thoughts",
    state: "empathy",
    environment: "shore",
    vector: "intensity",
    link: "waiting",
  },
  {
    id: 65,
    number: "#065",
    name: "Piotr",
    slug: "contemplator-065",
    phrase: "In the void built by habit, you choose not to flee from what you think; you wait and immerse yourself, because empathy, too, can be a form of descent.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989138/CONTEMPLATOR_65_s1lziz.png",
    object: "thoughts",
    state: "empathy",
    environment: "empty_space",
    vector: "immersion",
    link: "waiting",
  },
  {
    id: 66,
    number: "#066",
    name: "Steel",
    slug: "contemplator-066",
    phrase: "Silence settles over the shore with a calm that is not weakness; you watch it intensify, as if something very simple were about to reveal itself.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989175/CONTEMPLATOR_66_kv0dxa.png",
    object: "silence",
    state: "calm",
    environment: "shore",
    vector: "intensity",
    link: "observation",
  },
  {
    id: 67,
    number: "#067",
    name: "Flow",
    slug: "contemplator-067",
    phrase: "You attend to a silence made of particles and distance; empathy makes it near, and the abstract horizon begins to beat like a presence distributed through the air.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989189/CONTEMPLATOR_67_kc9syu.png",
    object: "silence",
    state: "empathy",
    environment: "horizon",
    vector: "abstraction",
    link: "attention",
  },
  {
    id: 68,
    number: "#068",
    name: "Perico",
    slug: "contemplator-068",
    phrase: "Among others, you perceive the vulnerability that usually hides beneath speed; empathy makes you attentive to that human lightness no one celebrates and everyone needs.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989185/CONTEMPLATOR_68_xzj6oo.png",
    object: "people",
    state: "empathy",
    environment: "crowded_place",
    vector: "lightness",
    link: "attention",
  },
  {
    id: 69,
    number: "#069",
    name: "Hardboy",
    slug: "contemplator-069",
    phrase: "Art inhabits this refuge like an ancient breeze over old metal; you observe it calmly, and its lightness ennobles even the hardest surfaces.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989186/CONTEMPLATOR_69_qu9f5y.png",
    object: "art",
    state: "calm",
    environment: "sacred_refuge",
    vector: "lightness",
    link: "observation",
  },
  {
    id: 70,
    number: "#070",
    name: "Fituro",
    slug: "contemplator-070",
    phrase: "Art speaks in its most secret phase, when it is still substance and promise; empathy brings you close to its shore, where depth works in silence.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989203/CONTEMPLATOR_70_rmijvq.png",
    object: "art",
    state: "empathy",
    environment: "shore",
    vector: "depth",
    link: "listening",
  },
  {
    id: 71,
    number: "#071",
    name: "Astrofit",
    slug: "contemplator-071",
    phrase: "Before the edge of art, you take nothing by assault: you open yourself. Its depth then enters with the patience of a tide that knows its hour.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989208/CONTEMPLATOR_71_kqtxtd.png",
    object: "art",
    state: "openness",
    environment: "shore",
    vector: "depth",
    link: "opening",
  },
  {
    id: 72,
    number: "#072",
    name: "Hoffmann",
    slug: "contemplator-072",
    phrase: "From the city's high murmur, art lets its brightness be heard; curiosity follows it across the horizon and discovers, beneath its lightness, a perfectly controlled fever.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989195/CONTEMPLATOR_72_r9qufq.png",
    object: "art",
    state: "curiosity",
    environment: "horizon",
    vector: "lightness",
    link: "listening",
  },
  {
    id: 73,
    number: "#073",
    name: "Lienzo Dorado",
    slug: "contemplator-073",
    phrase: "There are thoughts that look far because they come from very far back; you leave them before the horizon until nostalgia grants them a depth capable of holding you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989202/CONTEMPLATOR_73_g1hdor.png",
    object: "thoughts",
    state: "nostalgia",
    environment: "horizon",
    vector: "depth",
    link: "waiting",
  },
  {
    id: 74,
    number: "#074",
    name: "Anubis",
    slug: "contemplator-074",
    phrase: "You attend to people as if each one arrived creased by its own tide; your receptivity gives them back depth without requiring them to explain themselves.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989209/CONTEMPLATOR_74_amjsd4.png",
    object: "people",
    state: "openness",
    environment: "shore",
    vector: "depth",
    link: "attention",
  },
  {
    id: 75,
    number: "#075",
    name: "Velamber",
    slug: "contemplator-075",
    phrase: "In the geometric void surrounding people, you choose to attend to what cannot be named; empathy makes visible the abstraction of their weariness and their brightness.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989234/CONTEMPLATOR_75_b3lruc.png",
    object: "people",
    state: "empathy",
    environment: "empty_space",
    vector: "abstraction",
    link: "attention",
  },
  {
    id: 76,
    number: "#076",
    name: "Yellix",
    slug: "contemplator-076",
    phrase: "You observe how silence recomposes the world in fragments; curiosity does not break that order, it follows it, until the abstract acquires the serenity of a mosaic.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989195/CONTEMPLATOR_76_psyrgt.png",
    object: "silence",
    state: "curiosity",
    environment: "empty_space",
    vector: "abstraction",
    link: "observation",
  },
  {
    id: 77,
    number: "#077",
    name: "Carminior",
    slug: "contemplator-077",
    phrase: "Like a high, clear current, art crosses the horizon; its calm travels with such lightness that only the one who stills themselves can perceive it.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989194/CONTEMPLATOR_77_n3gufw.png",
    object: "art",
    state: "calm",
    environment: "horizon",
    vector: "lightness",
    link: "listening",
  },
  {
    id: 78,
    number: "#078",
    name: "Grisor",
    slug: "contemplator-078",
    phrase: "Nature does not arrive here pure, but mixed with the wear of the street; you open yourself to its intensity and discover that even the wounded can bloom.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989207/CONTEMPLATOR_78_uxnyga.png",
    object: "nature",
    state: "openness",
    environment: "crowded_place",
    vector: "intensity",
    link: "opening",
  },
  {
    id: 79,
    number: "#079",
    name: "Arturo",
    slug: "contemplator-079",
    phrase: "A silence saturated with color and surface lets itself be heard; you receive it with lightness, letting the void reveal its pulse without turning it into spectacle.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989141/CONTEMPLATOR_79_m3ptvn.png",
    object: "silence",
    state: "openness",
    environment: "empty_space",
    vector: "lightness",
    link: "listening",
  },
  {
    id: 80,
    number: "#080",
    name: "Cubic",
    slug: "contemplator-080",
    phrase: "Your thoughts break like a surf made of planes; empathy gathers them just enough for their intensity to cease being fragment and become direction.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989209/CONTEMPLATOR_80_twxofy.png",
    object: "thoughts",
    state: "empathy",
    environment: "shore",
    vector: "intensity",
    link: "listening",
  },
  {
    id: 81,
    number: "#081",
    name: "Citrux",
    slug: "contemplator-081",
    phrase: "Amid the noise, a citrus-bright, lively silence calls to you; you listen to it with curiosity and end up immersed in a clarity no one else seemed to suspect.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989126/CONTEMPLATOR_81_ipb0ny.png",
    object: "silence",
    state: "curiosity",
    environment: "crowded_place",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 82,
    number: "#082",
    name: "Arena",
    slug: "contemplator-082",
    phrase: "You attend to a monumental silence, as if the shore were made of mist and metal; nostalgia turns it abstract, and for that very reason impossible to abandon.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989127/CONTEMPLATOR_82_wdytja.png",
    object: "silence",
    state: "nostalgia",
    environment: "shore",
    vector: "abstraction",
    link: "attention",
  },
  {
    id: 83,
    number: "#083",
    name: "Tangerine",
    slug: "contemplator-083",
    phrase: "Inside a chamber of a single color, thought begins to answer; by receiving it without defense, the void gains depth and gives back a more mature voice.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989128/CONTEMPLATOR_83_qjj55m.png",
    object: "thoughts",
    state: "openness",
    environment: "empty_space",
    vector: "depth",
    link: "listening",
  },
  {
    id: 84,
    number: "#084",
    name: "Smith",
    slug: "contemplator-084",
    phrase: "Among signs, bodies, and flashes, you open yourself to human presence without reducing it to noise; thus you discover the depth that the crowd usually hides behind its speed.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989143/CONTEMPLATOR_84_wfmako.png",
    object: "people",
    state: "openness",
    environment: "crowded_place",
    vector: "depth",
    link: "opening",
  },
  {
    id: 85,
    number: "#085",
    name: "Nascimento",
    slug: "contemplator-085",
    phrase: "Calm does not extinguish vision: it sharpens it. Before the inner horizon, you open yourself to a hypnotic abstraction that sees for you what you still do not know how to name.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989218/CONTEMPLATOR_85_sdxupm.png",
    object: "thoughts",
    state: "calm",
    environment: "horizon",
    vector: "abstraction",
    link: "opening",
  },
  {
    id: 86,
    number: "#086",
    name: "Santoro",
    slug: "contemplator-086",
    phrase: "You observe silence in the heart of the future city; curiosity crosses through it, and the architectural void reveals a depth more human than its own lights.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989144/CONTEMPLATOR_86_gkhzbg.png",
    object: "silence",
    state: "curiosity",
    environment: "empty_space",
    vector: "depth",
    link: "observation",
  },
  {
    id: 87,
    number: "#087",
    name: "Moretti",
    slug: "contemplator-087",
    phrase: "Even with others around, nostalgia opens a separate silence within you; there the horizon darkens beautifully and depth becomes a form of shelter.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989129/CONTEMPLATOR_87_fsan5t.png",
    object: "silence",
    state: "nostalgia",
    environment: "crowded_place",
    vector: "depth",
    link: "opening",
  },
  {
    id: 88,
    number: "#088",
    name: "Wilson",
    slug: "contemplator-088",
    phrase: "A secret relief crosses the sky and you call it art; calm immerses you in its lines until the horizon ceases to be a background and becomes a path.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989144/CONTEMPLATOR_88_llu45c.png",
    object: "art",
    state: "calm",
    environment: "horizon",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 89,
    number: "#089",
    name: "Amrani",
    slug: "contemplator-089",
    phrase: "Nature appears here as a cold radiance inside an almost impossible structure; you open yourself to its lightness and feel that what is remote can also receive you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989148/CONTEMPLATOR_89_paqvwz.png",
    object: "nature",
    state: "openness",
    environment: "empty_space",
    vector: "lightness",
    link: "opening",
  },
  {
    id: 90,
    number: "#090",
    name: "Illuminati",
    slug: "contemplator-090",
    phrase: "You attend to the silence that survives within the crowd like a lit eye; empathy allows you to hold its intensity without extinguishing it or taming it.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989219/CONTEMPLATOR_90_xx5lra.png",
    object: "silence",
    state: "empathy",
    environment: "crowded_place",
    vector: "intensity",
    link: "attention",
  },
  {
    id: 91,
    number: "#091",
    name: "Gupta",
    slug: "contemplator-091",
    phrase: "You open yourself to a nature that already seems dream or mutation; in that refuge, calm stops nothing, it only immerses you in a beauty that keeps changing skin.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989149/CONTEMPLATOR_91_lhmfub.png",
    object: "nature",
    state: "calm",
    environment: "sacred_refuge",
    vector: "immersion",
    link: "opening",
  },
  {
    id: 92,
    number: "#092",
    name: "Sokolov",
    slug: "contemplator-092",
    phrase: "You attend to people with a frontal, almost pop calm, as if each one arrived at the shore of themselves seeking permission to enter.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989130/CONTEMPLATOR_92_mn2ryf.png",
    object: "people",
    state: "calm",
    environment: "shore",
    vector: "immersion",
    link: "attention",
  },
  {
    id: 93,
    number: "#093",
    name: "Restrepo",
    slug: "contemplator-093",
    phrase: "Your thoughts look far, but not with anxiety, rather with a sidereal calm; you attend to their lightness and the horizon becomes an expanding promise.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989150/CONTEMPLATOR_93_aufq1l.png",
    object: "thoughts",
    state: "calm",
    environment: "horizon",
    vector: "lightness",
    link: "attention",
  },
  {
    id: 94,
    number: "#094",
    name: "Montoya",
    slug: "contemplator-094",
    phrase: "From the cold of a distant architecture, people reach you like an echo; in receiving them, you discover that immersion, too, can be born in distance.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989154/CONTEMPLATOR_94_chj8bl.png",
    object: "people",
    state: "openness",
    environment: "empty_space",
    vector: "immersion",
    link: "listening",
  },
  {
    id: 95,
    number: "#095",
    name: "Boonmee",
    slug: "contemplator-095",
    phrase: "In the darkness of the refuge, curiosity lights two circles and that is enough; you open yourself to the intensity of an invisible nature that has never stopped looking at you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989131/CONTEMPLATOR_95_bv1ph0.png",
    object: "nature",
    state: "curiosity",
    environment: "sacred_refuge",
    vector: "intensity",
    link: "opening",
  },
  {
    id: 96,
    number: "#096",
    name: "Volkovych",
    slug: "contemplator-096",
    phrase: "You open yourself to art as one crosses a floor of ice and calculation; curiosity sustains you while the void reveals an exact, almost cruel depth.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989221/CONTEMPLATOR_96_yhflfq.png",
    object: "art",
    state: "curiosity",
    environment: "empty_space",
    vector: "depth",
    link: "opening",
  },
  {
    id: 97,
    number: "#097",
    name: "Vázquez",
    slug: "contemplator-097",
    phrase: "Ancient, almost human, silence sits in the refuge of memory; nostalgia gives it depth and you allow it to finish its discourse within you.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989226/CONTEMPLATOR_97_dyzwjn.png",
    object: "silence",
    state: "nostalgia",
    environment: "sacred_refuge",
    vector: "depth",
    link: "listening",
  },
  {
    id: 98,
    number: "#098",
    name: "Shade",
    slug: "contemplator-098",
    phrase: "Before the presence of others, you choose the delicacy of one who waits at the shore; empathy makes distance light and ennobles waiting.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989155/CONTEMPLATOR_98_nlco2i.png",
    object: "people",
    state: "empathy",
    environment: "shore",
    vector: "lightness",
    link: "waiting",
  },
  {
    id: 99,
    number: "#099",
    name: "Nyx",
    slug: "contemplator-099",
    phrase: "Distant presences pass through silence; nostalgia turns it abstract and the crowded place is transformed into a theater where no one dares break the spell.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989161/CONTEMPLATOR_99_owhehu.png",
    object: "silence",
    state: "nostalgia",
    environment: "crowded_place",
    vector: "abstraction",
    link: "listening",
  },
  {
    id: 100,
    number: "#100",
    name: "Petrauskas",
    slug: "contemplator-100",
    phrase: "You observe nature like a red edge in the half-light: minimal, sufficient. Empathy brings it near, and its lightness teaches you to look without possessing.",
    image: "https://res.cloudinary.com/dbinqzzol/image/upload/v1774989156/CONTEMPLATOR_100_bc9bri.png",
    object: "nature",
    state: "empathy",
    environment: "shore",
    vector: "lightness",
    link: "observation",
  },
];

/** Helper: get a Contemplator by its id (1..100) */
export function getContemplator(id: number): Contemplator | undefined {
  return CONTEMPLATORS.find((c) => c.id === id);
}

/** Helper: get a Contemplator by its slug (e.g. "contemplator-001") */
export function getContemplatorBySlug(slug: string): Contemplator | undefined {
  return CONTEMPLATORS.find((c) => c.slug === slug);
}
